# Search Methods

Suppose we have a model with different hyperparameters that need to be determined. To find the optimal values of these hyperparameters grid search and random search can be used. 

## Grid Search

Grid search involves creating a grid of values to search through. However this can be computationally heavy. For two variables a grid can look like:

In [1]:
import numpy as np
np.random.seed(42)

In [6]:
x = np.array([0, 1, 2, 3, 4]);
y = np.array([0, 1, 2, 3, 4]);
xx,yy = np.meshgrid(x,y)
print(xx)
print(yy)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


Now we can see that each value of x corresponds with each value of y to create a new point. This can be plotted or tested with hyperparameters

## Random Search

Random search is similar to grid search except it uses random values to search through. This is much more computationally efficient:

In [16]:
x = 5*np.random.rand(1,5)
y = 5*np.random.rand(1,5)
xx,yy = np.meshgrid(x,y)
print(xx)
print(yy)

[[0.61019117 2.47588455 0.17194261 4.54660201 1.29389991]
 [0.61019117 2.47588455 0.17194261 4.54660201 1.29389991]
 [0.61019117 2.47588455 0.17194261 4.54660201 1.29389991]
 [0.61019117 2.47588455 0.17194261 4.54660201 1.29389991]
 [0.61019117 2.47588455 0.17194261 4.54660201 1.29389991]]
[[3.31261142 3.31261142 3.31261142 3.31261142 3.31261142]
 [1.55855538 1.55855538 1.55855538 1.55855538 1.55855538]
 [2.60034011 2.60034011 2.60034011 2.60034011 2.60034011]
 [2.7335514  2.7335514  2.7335514  2.7335514  2.7335514 ]
 [0.92427228 0.92427228 0.92427228 0.92427228 0.92427228]]


Usually first a random search is used and later a grid search can search around the best random value.